"""sdde

Revision ID: edf12266c0c4
Revises: cc31de0cbd9d
Create Date: 2023-04-24 11:09:04.932312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edf12266c0c4'
down_revision = 'cc31de0cbd9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('address', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('address', 'id')
    op.drop_column('address', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('longitude', sa.FLOAT(), nullable=True))
    op.add_column('address', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('address', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('address', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
